// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hexrunner-onboarding/CinematicTerritory.tsx": () => import("../components/mockups/hexrunner-onboarding/CinematicTerritory.tsx")
};
