// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hexrunner-onboarding/CinematicTerritory.tsx": () => import("../components/mockups/hexrunner-onboarding/CinematicTerritory.tsx"),
  "./components/mockups/hexrunner-redesign/Home.tsx": () => import("../components/mockups/hexrunner-redesign/Home.tsx"),
  "./components/mockups/hexrunner-redesign/Launch.tsx": () => import("../components/mockups/hexrunner-redesign/Launch.tsx"),
  "./components/mockups/hexrunner-redesign/Leaderboard.tsx": () => import("../components/mockups/hexrunner-redesign/Leaderboard.tsx"),
  "./components/mockups/hexrunner-redesign/Profile.tsx": () => import("../components/mockups/hexrunner-redesign/Profile.tsx")
};
