import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Activity, Crosshair, Layers2, Navigation, Play, Trophy, UserRound } from "lucide-react";
import "./_group.css";
const hexes=[["20%","28%","mine"],["35%","22%","mine"],["50%","27%","rival"],["65%","22%","mine"],["27%","43%","mine"],["42%","39%","mine"],["57%","44%","rival"],["72%","42%","rival"],["35%","58%","mine"],["50%","57%","mine"],["65%","60%","mine"]];
export function Home() {
 const [arrival,setArrival]=useState(true); const [running,setRunning]=useState(false); const [tab,setTab]=useState("MAP");
 return <main className="hr-shell bg-[#0a1519]">
  <div className="absolute inset-0 bg-[#101c20] hr-grid"/><div className="absolute inset-0 opacity-80" style={{backgroundImage:"linear-gradient(24deg,transparent 48%,#4c6061 49%,transparent 50%),linear-gradient(116deg,transparent 48%,#4c6061 49%,transparent 50%),linear-gradient(0deg,transparent 48%,#394f53 49%,transparent 50%)",backgroundSize:"72px 96px,88px 112px,100px 125px"}}/>
  {hexes.map(([x,y,t],i)=><motion.div initial={{scale:0,opacity:0}} animate={{scale:1,opacity:1}} transition={{delay:1.7+i*.06}} key={i} className={`absolute h-[76px] w-[87px] hr-hex border ${t==="mine"?"border-[#9cf04a]/75 bg-[#9cf04a]/20":"border-[#ff677c]/60 bg-[#ff677c]/13"}`} style={{left:x,top:y}}/>)}
  <div className="absolute left-[46%] top-[46%] z-10 grid h-11 w-11 place-items-center rounded-full border-4 border-[#f4f7ee] bg-[#9cf04a] shadow-[0_0_0_9px_rgba(156,240,74,.15)]"><Navigation size={18} fill="#0b1518" className="text-[#0b1518]"/></div>
  <header className="absolute top-0 z-20 flex w-full items-start justify-between px-5 pt-7"><div className="hr-glass px-3 py-2"><p className="hr-mono text-[9px] tracking-[.14em] text-[#a5b7b0]">YOUR TERRITORY</p><p className="hr-display text-2xl"><span className="text-[#9cf04a]">2.84</span> KM²</p></div><button className="hr-glass grid h-11 w-11 place-items-center rounded-full"><Layers2 size={18}/></button></header>
  <div className="absolute right-5 top-36 z-20 flex flex-col gap-2"><button className="hr-glass grid h-10 w-10 place-items-center rounded-full"><Crosshair size={17}/></button><button className="hr-glass grid h-10 w-10 place-items-center rounded-full"><Activity size={17}/></button></div>
  <div className="absolute bottom-[164px] z-20 w-full px-5"><div className="hr-glass rounded-sm p-4"><div className="flex items-center justify-between"><div><p className="hr-mono text-[10px] tracking-[.14em] text-[#9cf04a]">TONIGHT'S WINDOW</p><h2 className="hr-display mt-1 text-[28px] leading-none">18 BLOCKS OPEN</h2></div><span className="hr-mono text-[11px] text-[#b6c7c0]">1.2 KM</span></div><div className="mt-3 h-1.5 overflow-hidden bg-[#d5e5dc]/15"><div className="h-full w-[64%] bg-[#9cf04a]"/></div><p className="mt-2 text-[11px] text-[#aabbb4]">6 rival blocks in range. Run a loop to take them.</p></div></div>
  <nav className="absolute bottom-0 z-20 flex h-[84px] w-full items-start justify-around bg-[#0a1216]/95 px-3 pt-3 backdrop-blur"><button onClick={()=>setTab("MAP")} className={`grid place-items-center gap-1 text-[9px] ${tab==="MAP"?"text-[#9cf04a]":"text-[#96aaa2]"}`}><Layers2 size={19}/><span>MAP</span></button><button onClick={()=>setRunning(!running)} className="relative -top-7 grid h-[66px] w-[66px] place-items-center rounded-full border-[5px] border-[#0a1216] bg-[#9cf04a] text-[#081013]"><Play size={24} fill="currentColor"/></button><button onClick={()=>setTab("RANK")} className={`grid place-items-center gap-1 text-[9px] ${tab==="RANK"?"text-[#9cf04a]":"text-[#96aaa2]"}`}><Trophy size={19}/><span>RANK</span></button><button onClick={()=>setTab("YOU")} className={`grid place-items-center gap-1 text-[9px] ${tab==="YOU"?"text-[#9cf04a]":"text-[#96aaa2]"}`}><UserRound size={19}/><span>YOU</span></button></nav>
  <AnimatePresence>{arrival&&<motion.div initial={{opacity:1}} exit={{opacity:0}} onClick={()=>setArrival(false)} className="absolute inset-0 z-30 grid place-items-center bg-[#071015]"><motion.div initial={{scale:3,opacity:0}} animate={{scale:1,opacity:1}} transition={{duration:1.1}} className="relative"><div className="h-52 w-52 rounded-full border border-[#92e8d1]/30 bg-[radial-gradient(circle_at_35%_30%,#4d8586,#17323a_55%,#071015)] shadow-[0_0_0_35px_rgba(100,196,178,.04)]"/><div className="absolute left-1/2 top-1/2 h-24 w-24 -translate-x-1/2 -translate-y-1/2 hr-hex border border-[#9cf04a]"/></motion.div><div className="absolute bottom-28 text-center"><p className="hr-mono text-[10px] tracking-[.22em] text-[#9cf04a]">ARRIVING AT</p><h1 className="hr-display mt-2 text-4xl">SOUTH BANK</h1><p className="mt-2 text-xs text-[#bccac3]">London · precise GPS lock</p><button className="mt-5 text-xs underline underline-offset-4">Tap to enter map</button></div></motion.div>}</AnimatePresence>
  {running&&<motion.div initial={{y:90}} animate={{y:0}} className="absolute bottom-20 z-30 w-full px-5"><div className="flex items-center justify-between bg-[#9cf04a] px-4 py-3 text-[#081013]"><span className="hr-display text-xl">RUN ARMED</span><span className="hr-mono text-[11px]">00:00:00</span></div></motion.div>}
 </main>
}