import { useState } from "react";
import { motion } from "framer-motion";
import { ChevronDown, Crown, Medal, Navigation, Trophy, UserRound } from "lucide-react";
import "./_group.css";
const ranks=[["Mira Okafor","4,826","142","MO"],["Kai Nørgaard","4,510","131","KN"],["Sofia Ren","4,286","119","SR"],["Jules Morrow","3,942","114","JM"],["YOU / Devon","3,738","106","DV"],["Tomas Vela","3,596","98","TV"]];
export function Leaderboard(){
 const [scope,setScope]=useState("CITY"); const [filter,setFilter]=useState(false);
 return <main className="hr-shell hr-grid overflow-hidden">
  <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_90%_7%,#17414b,transparent_40%),#091216]"/>
  <header className="relative z-10 px-5 pt-7"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><img src="/__mockup/images/hexrunner-mark-v2.svg" className="h-8 w-7"/><span className="hr-display text-[22px]">HEXRUNNER</span></div><button onClick={()=>setFilter(!filter)} className="hr-glass flex items-center gap-1 px-3 py-2"><span className="hr-mono text-[9px]">THIS WEEK</span><ChevronDown size={14}/></button></div><p className="hr-mono mt-8 text-[10px] tracking-[.18em] text-[#9cf04a]">TERRITORY LEADERBOARD</p><h1 className="hr-display mt-1 text-[55px] leading-[.76]">THE<br/>NIGHT SHIFT.</h1></header>
  <div className="relative z-10 mt-7 flex gap-2 px-5">{["GLOBAL","CITY","RIVALS"].map(s=><button onClick={()=>setScope(s)} key={s} className={`flex-1 border py-2.5 text-[10px] font-semibold tracking-[.08em] ${scope===s?"border-[#9cf04a] bg-[#9cf04a] text-[#071114]":"border-[#c4d5cc]/20 text-[#aebeb7]"}`}>{s}</button>)}</div>
  <section className="relative z-10 mt-5 px-5"><div className="flex items-center justify-between border-b border-[#b9d3c7]/15 pb-2"><span className="hr-mono text-[9px] tracking-[.12em] text-[#829790]">RANK / RUNNER</span><span className="hr-mono text-[9px] tracking-[.12em] text-[#829790]">CREDITS</span></div>
   <div>{ranks.map(([name,credits,hexes,init],i)=>{const mine=name.startsWith("YOU");return <motion.div initial={{opacity:0,x:15}} animate={{opacity:1,x:0}} transition={{delay:i*.08}} key={name} className={`flex items-center gap-3 border-b border-[#b9d3c7]/10 py-[13px] ${mine?"-mx-2 bg-[#9cf04a]/12 px-2":"px-1"}`}><div className="w-5 text-center">{i<3?<Medal size={17} className={i===0?"text-[#9cf04a]":i===1?"text-[#b7cad0]":"text-[#d89163]"}/>:<span className="hr-display text-xl text-[#778a84]">{i+1}</span>}</div><div className={`grid h-9 w-9 place-items-center rounded-full text-[10px] font-bold ${mine?"bg-[#9cf04a] text-[#081316]":"bg-[#1b2b30] text-[#c8d8d0]"}`}>{init}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-[13px] font-semibold">{name}</p>{mine&&<span className="hr-mono bg-[#9cf04a] px-1.5 py-[2px] text-[8px] text-[#081316]">YOU</span>}</div><p className="mt-0.5 text-[10px] text-[#829790]">{hexes} hexes held</p></div><div className="text-right"><p className="hr-display text-[24px] leading-none">{credits}</p><p className="hr-mono mt-1 text-[8px] tracking-[.1em] text-[#9cf04a]">CREDITS</p></div></motion.div>})}</div>
  </section>
  <div className="absolute bottom-0 z-10 flex h-[70px] w-full items-center justify-around border-t border-[#b9d3c7]/10 bg-[#0a1317] text-[#8ea19a]"><Navigation size={18}/><button className="grid h-10 w-10 place-items-center rounded-full bg-[#1c3133]"><Trophy size={18} className="text-[#9cf04a]"/></button><UserRound size={18}/></div>
  {filter&&<div className="absolute right-5 top-14 z-30 w-40 border border-[#9cf04a]/30 bg-[#102025] p-3 text-xs shadow-xl"><p className="text-[#9cf04a]">This week</p><p className="mt-3 text-[#b9c9c2]">All time</p><p className="mt-3 text-[#b9c9c2]">Last night</p></div>}
 </main>
}