import { useState } from "react";
import { Activity, ChevronRight, Map, Settings2, ShieldAlert, Zap } from "lucide-react";
import "./_group.css";
const runs=[["TONIGHT · 21:14","5.42 km","+18","32"],["TUE · 20:48","7.08 km","+24","41"]];
export function Profile(){
 const [colour,setColour]=useState("#9cf04a"); const [notice,setNotice]=useState(false);
 return <main className="hr-shell hr-grid overflow-y-auto">
  <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_20%_0%,#193e40,transparent_34%),#091216]"/>
  <header className="flex items-center justify-between px-5 pt-7"><div className="flex items-center gap-2"><img src="/__mockup/images/hexrunner-mark-v2.svg" className="h-8 w-7"/><span className="hr-display text-[22px]">HEXRUNNER</span></div><button onClick={()=>setNotice(true)} className="hr-glass grid h-10 w-10 place-items-center rounded-full"><Settings2 size={17}/></button></header>
  <section className="px-5 pt-7"><p className="hr-mono text-[10px] tracking-[.16em] text-[#9cf04a]">RUNNER FILE / ACTIVE</p><div className="mt-3 flex items-end justify-between"><div><h1 className="hr-display text-[51px] leading-[.78]">DEVON<br/>KERR.</h1><p className="mt-3 text-[11px] text-[#9badA5]">SOUTH BANK · LONDON</p></div><div className="grid h-16 w-16 place-items-center rounded-full border-2 border-[#9cf04a] bg-[#183136]"><span className="hr-display text-[30px] text-[#9cf04a]">DK</span></div></div></section>
  <section className="mx-5 mt-6 border border-[#9cf04a]/45 bg-[#9cf04a]/[.08] p-4"><div className="flex items-center justify-between"><div><p className="hr-mono text-[9px] tracking-[.14em] text-[#9cf04a]">FITNESS TIER</p><p className="hr-display mt-1 text-[31px]">PACE MAKER</p></div><div className="text-right"><p className="hr-display text-[35px] text-[#9cf04a]">07</p><p className="hr-mono text-[8px] text-[#a8bab2]">DAY STREAK</p></div></div><div className="mt-3 h-1.5 bg-[#d2e7da]/15"><div className="h-full w-[71%] bg-[#9cf04a]"/></div><p className="mt-2 text-[10px] text-[#a9bbb3]">29 hexes to reach Night Runner</p></section>
  <section className="mt-5 px-5"><div className="grid grid-cols-2 gap-2"><div className="col-span-2 border border-[#b5cec2]/15 bg-[#122126] p-3"><p className="hr-mono text-[9px] tracking-[.12em] text-[#8fa29a]">TOTAL CREDITS</p><p className="hr-display mt-1 text-[40px] leading-none">3,738</p></div>{[["TERRITORY","284","HEXES"],["RUNS","46","LOGGED"],["DISTANCE","318.7","KM"],["BONUS","462","EARNED"]].map(([a,b,c])=><div className="border border-[#b5cec2]/12 bg-[#0d191d] p-3" key={a}><p className="hr-mono text-[8px] tracking-[.1em] text-[#8fa29a]">{a}</p><p className="hr-display mt-2 text-[27px] leading-none">{b}</p><p className="mt-1 text-[8px] text-[#9cf04a]">{c}</p></div>)}</div></section>
  <section className="mt-5 px-5"><p className="hr-mono text-[10px] tracking-[.15em] text-[#a7b7b0]">TERRITORY SIGNAL</p><div className="mt-3 flex gap-3">{["#9cf04a","#25c9ed","#f29a52","#ef627e"].map(c=><button onClick={()=>setColour(c)} key={c} className={`h-9 w-9 hr-hex ${colour===c?"ring-2 ring-white ring-offset-2 ring-offset-[#091216]":""}`} style={{background:c}}/>)}</div></section>
  <section className="mt-6 px-5 pb-8"><div className="mb-2 flex items-center justify-between"><p className="hr-display text-[25px]">RECENT RUNS</p><button className="text-[10px] text-[#9cf04a]">VIEW ALL</button></div>{runs.map(([date,dist,credit,hex])=><button key={date} className="mb-2 flex w-full items-center gap-3 border border-[#b5cec2]/12 bg-[#0d191d] p-3 text-left"><div className="grid h-9 w-9 place-items-center bg-[#183136]"><Activity size={16} className="text-[#9cf04a]"/></div><div className="flex-1"><p className="text-[11px] font-semibold">{date}</p><p className="mt-1 text-[10px] text-[#94a69f]">{dist} · {hex} claimed</p></div><p className="hr-display text-xl text-[#9cf04a]">{credit}</p><ChevronRight size={15} className="text-[#81938c]"/></button>)}</section>
  {notice&&<div onClick={()=>setNotice(false)} className="fixed inset-0 z-30 grid place-items-center bg-[#061014]/80 px-6"><div className="border border-[#9cf04a]/40 bg-[#102126] p-5 text-center"><ShieldAlert className="mx-auto text-[#9cf04a]"/><p className="hr-display mt-3 text-2xl">SETTINGS LOCKED</p><p className="mt-2 text-xs text-[#b5c6be]">Runner preferences open in the full app.</p><button className="mt-4 text-xs text-[#9cf04a]">DISMISS</button></div></div>}
 </main>
}